name = "HW1"
uuid = "af5674cc-1e0f-11e9-223f-c3fb9d74540d"
authors = ["Nicholas Todoroff <loppy1243@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
